import uuid from 'uuid/v1';

export default [
  {
    id: uuid(),
    name: 'Ekaterina Tankova',
    positivesApplicants: 4,
    negativeApplicants: 5,
    suspiciousApplicants: 2,
    avatarUrl: '/images/avatars/avatar_3.png',
  },
  {
    id: uuid(),
    name: 'Cao Yu',
    positivesApplicants: 12,
    negativeApplicants: 23,
    suspiciousApplicants: 1,
    avatarUrl: '/images/avatars/avatar_4.png',
    phone: '712-351-5711',
  },
  {
    id: uuid(),
    name: 'Alexa Richardson',
    positivesApplicants: 2,
    negativeApplicants: 12,
    suspiciousApplicants: 6,
    avatarUrl: '/images/avatars/avatar_2.png',
  },
  {
    id: uuid(),
    name: 'Anje Keizer',
    positivesApplicants: 3,
    negativeApplicants: 21,
    suspiciousApplicants: 21,
    avatarUrl: '/images/avatars/avatar_5.png',
  },
  {
    id: uuid(),
    name: 'Clarke Gillebert',
    positivesApplicants: 41,
    negativeApplicants: 61,
    suspiciousApplicants: 12,
    avatarUrl: '/images/avatars/avatar_6.png',
  },
  {
    id: uuid(),
    name: 'Adam Denisov',
    positivesApplicants: 2,
    negativeApplicants: 6,
    suspiciousApplicants: 21,
    avatarUrl: '/images/avatars/avatar_1.png',
  },
  {
    id: uuid(),
    name: 'Ava Gregoraci',
    positivesApplicants: 28,
    negativeApplicants: 83,
    suspiciousApplicants: 19,
    avatarUrl: '/images/avatars/avatar_7.png',
  },
  {
    id: uuid(),
    name: 'Emilee Simchenko',
    positivesApplicants: 18,
    negativeApplicants: 13,
    suspiciousApplicants: 5,
    avatarUrl: '/images/avatars/avatar_8.png',
  },
  {
    id: uuid(),
    name: 'Kwak Seong-Min',
    positivesApplicants: 41,
    negativeApplicants: 24,
    suspiciousApplicants: 16,
    avatarUrl: '/images/avatars/avatar_9.png',
  },
  {
    id: uuid(),
    name: 'Merrile Burgett',
    positivesApplicants: 57,
    negativeApplicants: 34,
    suspiciousApplicants: 12,
    avatarUrl: '/images/avatars/avatar_10.png',
  }
];
